//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoc_vien
    {
        public int ma_hv { get; set; }
        public string ma_sv { get; set; }
        public int ma_lh { get; set; }
        public Nullable<double> diem { get; set; }
        public string nhan_xet { get; set; }
    
        public virtual lop_hoc lop_hoc { get; set; }
        public virtual sinh_vien sinh_vien { get; set; }
    }
}
