//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class lop_hoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lop_hoc()
        {
            this.hoc_vien = new HashSet<hoc_vien>();
        }
    
        public int ma_lh { get; set; }
        public string ma_mh { get; set; }
        public string ma_gv { get; set; }
        public string ma_hk { get; set; }
    
        public virtual giang_vien giang_vien { get; set; }
        public virtual hoc_ky hoc_ky { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoc_vien> hoc_vien { get; set; }
        public virtual mon_hoc mon_hoc { get; set; }
    }
}
