//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dangnhap
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeHoi
    {
        public int MaXe { get; set; }
        public string TenXe { get; set; }
        public string Kho { get; set; }
        public Nullable<System.DateTime> NgayNhapKho { get; set; }
        public int MaLoai { get; set; }
    
        public virtual Kho Kho1 { get; set; }
        public virtual LoaiXe LoaiXe { get; set; }
    }
}
